name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run bash-environment-manager      
      run: |
        curl https://raw.githubusercontent.com/terminal-labs/bash-environment-shelf/master/prepscripts/mock_vagrant.sh --output .repo/mock_vagrant.sh
        sudo bash .repo/mock_vagrant.sh
        chmod 700 /home/vagrant/.ssh
        chown -R vagrant /home/vagrant/.ssh
        cd /vagrant
        sudo bash deps.sh
        ssh-keygen -t rsa -f /home/vagrant/.ssh/id_rsa -q -P ""
        sudo su vagrant -c 'cd /vagrant; source /home/vagrant/miniconda3/etc/profile.d/conda.sh; source /home/vagrant/.bashrc;  conda activate runner'
        sudo su vagrant -c 'cd /vagrant; bash setup.sh'
